# Generated by ard-make version 1.2
ARDUINO_DIR=/opt/arduino-1.8.8/
ARDMK_DIR=/usr/share/arduino
AVR_TOOLS_DIR=/opt/arduino-1.8.8/hardware/tools/avr/

BOARD_TAG = nano
BOARD_SUB = atmega328
MONITOR_PORT = /dev/ttyUSB0

include $(ARDMK_DIR)/Arduino.mk
